# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CRABui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CRAB(object):
    def setupUi(self, CRAB):
        CRAB.setObjectName("CRAB")
        CRAB.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(CRAB)
        self.centralwidget.setObjectName("centralwidget")
        self.BG1 = QtWidgets.QLabel(self.centralwidget)
        self.BG1.setGeometry(QtCore.QRect(0, -10, 1921, 1101))
        self.BG1.setText("")
        self.BG1.setPixmap(QtGui.QPixmap("gui CRAB/B.G/Black_Template.jpg"))
        self.BG1.setScaledContents(True)
        self.BG1.setObjectName("BG1")
        self.gif1 = QtWidgets.QLabel(self.centralwidget)
        self.gif1.setGeometry(QtCore.QRect(630, 150, 641, 501))
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("gui CRAB/VoiceReg/Siri_1.gif"))
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(580, 20, 361, 101))
        self.Time.setStyleSheet("background-color:transparent;\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);\n"
"font: 75 24pt \"Microsoft JhengHei\";")
        self.Time.setObjectName("Time")
        self.date = QtWidgets.QTextBrowser(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(950, 20, 361, 101))
        self.date.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);\n"
"font: 75 24pt \"Microsoft JhengHei\";")
        self.date.setObjectName("date")
        self.START_button = QtWidgets.QPushButton(self.centralwidget)
        self.START_button.setGeometry(QtCore.QRect(300, 400, 301, 71))
        self.START_button.setStyleSheet("background-color: Transparent;\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);\n"
"font: 75 24pt \"Microsoft JhengHei\";")
        self.START_button.setObjectName("START_button")
        self.EXIT_button = QtWidgets.QPushButton(self.centralwidget)
        self.EXIT_button.setGeometry(QtCore.QRect(1260, 400, 301, 71))
        self.EXIT_button.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"color: rgb(0, 255, 255);\n"
"font: 75 24pt \"Microsoft YaHei\";")
        self.EXIT_button.setObjectName("EXIT_button")
        self.Temprature = QtWidgets.QTextBrowser(self.centralwidget)
        self.Temprature.setGeometry(QtCore.QRect(720, 700, 461, 192))
        self.Temprature.setStyleSheet("background-color: Transparent;\n"
"border-radius:none;")
        self.Temprature.setObjectName("Temprature")
        self.YouTube_button = QtWidgets.QPushButton(self.centralwidget)
        self.YouTube_button.setGeometry(QtCore.QRect(370, 560, 151, 51))
        self.YouTube_button.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: Transparent;\n"
"border-radius:none;")
        self.YouTube_button.setObjectName("YouTube_button")
        self.chrome_button = QtWidgets.QPushButton(self.centralwidget)
        self.chrome_button.setGeometry(QtCore.QRect(1330, 540, 151, 51))
        self.chrome_button.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: transparent;\n"
"border-radius:none;")
        self.chrome_button.setObjectName("chrome_button")
        CRAB.setCentralWidget(self.centralwidget)

        self.retranslateUi(CRAB)
        QtCore.QMetaObject.connectSlotsByName(CRAB)

    def retranslateUi(self, CRAB):
        _translate = QtCore.QCoreApplication.translate
        CRAB.setWindowTitle(_translate("CRAB", "MainWindow"))
        self.START_button.setText(_translate("CRAB", "START"))
        self.EXIT_button.setText(_translate("CRAB", "EXIT"))
        self.YouTube_button.setText(_translate("CRAB", "YouTube"))
        self.chrome_button.setText(_translate("CRAB", "Google"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CRAB = QtWidgets.QMainWindow()
    ui = Ui_CRAB()
    ui.setupUi(CRAB)
    CRAB.show()
    sys.exit(app.exec_())
